{ pkgs, ... }:
with pkgs;
[
  devenv
  fastfetch
  vscode
  nil
  nixfmt-rfc-style
  rust-analyzer
  rustfmt
  cargo
  gcc
  nodePackages.svelte-language-server
  nodePackages.typescript-language-server
  vscode-langservers-extracted
  nodePackages.prettier
  nodePackages.typescript
  emmet-ls
  pnpm
  maven
  linuxKernel.packages.linux_6_11.perf
  libreoffice
  jetbrains.idea-ultimate
  jetbrains.pycharm-professional
  shotcut
  swaylock-effects
  firefox
  fusuma
  waybar
  mako
  wl-clipboard
  hyprshot
  hyprpicker
  light
  pavucontrol
  wlogout
  webcord
  btop
  obs-studio
  vlc
  playerctl
  nodejs
  pulseaudio
  brightnessctl
]
