keys:
  - &hayshin age17zt3msa40psgf4d2c5clqau8gmxm68045u07q5h7eyvq28z7yq4q9q2dz3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *hayshin
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *hayshin
